= Doc-tracing

Repository dedicated to the talks about https://pypi.org/project/pydoctrace/[pydoctrace].
It is a mix of English and French talks.

== Slideshows

. link:2023.04.06-doc-tracing_quicky_fr.adoc[2023.04.06-doc-tracing_quicky_fr.adoc], _quicky_ given during the https://events.rennes.tech/events/f99fc1e8-66a3-4753-a8bb-2f32c3e67b53[Evening with the technical communities of Rennes] (Brittany, France, 🇫🇷French contents)

== View the slideshow·s

The slideshows were designed to be displayed using the https://marketplace.visualstudio.com/items?itemName=flobilosaurus.vscode-asciidoc-slides[flobilosaurus.vscode-asciidoc-slides] extension for Codium / vsCode.

. display the commands with `ctrl shift p`
. use the `Asciidoc Slides: Open Slides in Browser` command

Documentation about the https://docs.asciidoctor.org/reveal.js-converter/latest/converter/features/[Asciidoc syntax for slideshows].

== Export as a PDF file

. use the `Asciidoc Slides: Export document as PDF` command (it does not always work)

or :

. open the slideshow with chromium or chrome
. add `?print-pdf` at the end of the URL
. print as a PDF with `ctrl p` ou `cmd p`


== Code examples

This repository involves code samples and libraries which generate documentation:

[source,sh]
----
# installs the appropriate python version (otherwise 3.10+ should be ok)
pyenv install $(cat .python-version)

# creates a virtual environment
python - m venv .venv

# activates the virtual environment
source .venv/bin/activate

# installs the libraries
pip install -r requirements.txt
----
